[package]
name = "pompeii"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38"
ash-window = "0.13"
inline-spirv = "0.2.1"
shaderc = "0.8"
smallvec = "1.13"
strum = "0.26"
strum_macros = "0.26"
winit = "0.30"
